---
version: '3'
services:
  mysql:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/setup.sql
       - db_data:/var/lib/mysql
volumes:
   db_data:
