openapi: 3.0.3
info:
  title: FörsäkringGirot
  description: FörsäkringGirot Assignment API
  version: 1.0.0
paths:
  /api/chilifruits:
    get:
      summary: Get chilifruits from DB
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChiliFruit'
        '400':
          description: No data in DB

  /api/chilifruits/{id}/updateQuantity:
    post:
      summary: Update Quantity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newQuantity:
                  type: integer
              required:
                - newQuantity
      responses:
        '200':
          description: Quantity updated successfully
        '400':
          description: Quantity cannot be negative
        '404':
          description: Chili fruit not found

components:
  schemas:
    ChiliFruit:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        origin:
          type: string
        scoville:
          type: integer
          format: int32
        unitPrice:
          type: number
          format: float
        quantity:
          type: integer
          format: int32
